export enum VoteVariantEnum {
    UPVOTE = 'UPVOTE',
    DOWNVOTE = 'DOWNVOTE',
}

export enum FeatureStatusEnum {
    NEW = 'NEW',
    SHIPPED = 'SHIPPED',
    PLANNED = 'PLANNED',
    REJECTED = 'REJECTED',
    IN_PROGRESS = 'IN_PROGRESS',
    UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum FeatureCategoryEnum {
    OTHER = 'OTHER',
    UI_UX = 'UI_UX',
    SPLITR = 'SPLITR',
    PROFILE = 'PROFILE',
    ACCOUNTS = 'ACCOUNTS',
    ANALYSIS = 'ANALYSIS',
    SECURITY = 'SECURITY',
    BUDGETING = 'BUDGETING',
    BUG_REPORT = 'BUG_REPORT',
    PERFORMANCE = 'PERFORMANCE',
    NEW_FEATURE = 'NEW_FEATURE',
    TRANSACTIONS = 'TRANSACTIONS',
    BILLS_AND_GOALS = 'BILLS_AND_GOALS',
}