export enum GoalCategoryEnum {
  LOAN = 'LOAN',
  TRAVEL = 'TRAVEL',
  SAVINGS = 'SAVINGS',
  PURCHASE = 'PURCHASE',
  VACATION = 'VACATION',
  EDUCATION = 'EDUCATION',
  RETIREMENT = 'RETIREMENT',
  INVESTMENTS = 'INVESTMENTS',
  DEBT_PAYMENT = 'DEBT_PAYMENT',
  EMERGENCY_FUND = 'EMERGENCY_FUND',
  OTHER = 'OTHER',
}

export enum GoalStatusEnum {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
}
