export enum GoalCategoryEnum {
  OTHER = 'OTHER',
  TRAVEL = 'TRAVEL',
  SAVINGS = 'SAVINGS',
  VACATION = 'VACATION',
  EDUCATION = 'EDUCATION',
  RETIREMENT = 'RETIREMENT',
  INVESTMENTS = 'INVESTMENTS',
  HOME_PURCHASE = 'HOME_PURCHASE',
  DEBT_REDUCTION = 'DEBT_REDUCTION',
  EMERGENCY_FUND = 'EMERGENCY_FUND',
}

export enum GoalStatusEnum {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
}
