export enum GoalCategoryEnum {
  SAVINGS = 'SAVINGS',
  INVESTMENTS = 'INVESTMENTS',
  DEBT_REDUCTION = 'DEBT_REDUCTION',
  EMERGENCY_FUND = 'EMERGENCY_FUND',
  RETIREMENT = 'RETIREMENT',
  EDUCATION = 'EDUCATION',
  TRAVEL = 'TRAVEL',
  HOME_PURCHASE = 'HOME_PURCHASE',
  VACATION = 'VACATION',
  OTHER = 'OTHER',
}
