import { LabelValueItem } from "../types";

export const MONTHS_ENUM: LabelValueItem[] = [
  { value: "january", label: "January" },
  { value: "february", label: "February" },
  { value: "march", label: "March" },
  { value: "april", label: "April" },
  { value: "may", label: "May" },
  { value: "june", label: "June" },
  { value: "july", label: "July" },
  { value: "august", label: "August" },
  { value: "september", label: "September" },
  { value: "october", label: "October" },
  { value: "november", label: "November" },
  { value: "december", label: "December" },
];

export const LANGUAGES: LabelValueItem[] = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "it", label: "Italian" },
  { value: "pt", label: "Portuguese" },
  { value: "ru", label: "Russian" },
  { value: "zh", label: "Chinese" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "ar", label: "Arabic" },
  { value: "hi", label: "Hindi" },
  { value: "bn", label: "Bengali" },
  { value: "pa", label: "Punjabi" },
  { value: "ur", label: "Urdu" },
  { value: "tr", label: "Turkish" },
  { value: "nl", label: "Dutch" },
  { value: "sv", label: "Swedish" },
  { value: "no", label: "Norwegian" },
  { value: "da", label: "Danish" },
  { value: "fi", label: "Finnish" },
  { value: "el", label: "Greek" },
  { value: "cs", label: "Czech" },
  { value: "hu", label: "Hungarian" },
  { value: "pl", label: "Polish" },
  { value: "ro", label: "Romanian" },
  { value: "bg", label: "Bulgarian" },
  { value: "sr", label: "Serbian" },
  { value: "hr", label: "Croatian" },
  { value: "sl", label: "Slovenian" },
  { value: "sk", label: "Slovak" },
  { value: "et", label: "Estonian" },
  { value: "lv", label: "Latvian" },
  { value: "lt", label: "Lithuanian" },
  { value: "he", label: "Hebrew" },
  { value: "th", label: "Thai" },
  { value: "id", label: "Indonesian" },
  { value: "ms", label: "Malay" },
  { value: "vi", label: "Vietnamese" },
  { value: "tl", label: "Tagalog" },
  { value: "sw", label: "Swahili" },
  { value: "am", label: "Amharic" },
  { value: "ha", label: "Hausa" },
  { value: "yo", label: "Yoruba" },
  { value: "ig", label: "Igbo" },
  { value: "zu", label: "Zulu" },
  { value: "af", label: "Afrikaans" },
  { value: "xh", label: "Xhosa" },
  { value: "tn", label: "Tswana" },
  { value: "st", label: "Sotho" },
  { value: "ts", label: "Tsonga" },
  { value: "ss", label: "Swati" },
  { value: "ve", label: "Venda" },
  { value: "nr", label: "Ndebele" },
  { value: "ku", label: "Kurdish" },
  { value: "fa", label: "Persian" },
  { value: "ps", label: "Pashto" },
  { value: "sd", label: "Sindhi" },
  { value: "ne", label: "Nepali" },
  { value: "si", label: "Sinhala" },
  { value: "my", label: "Myanmar" },
  { value: "km", label: "Khmer" },
  { value: "lo", label: "Lao" },
  { value: "mn", label: "Mongolian" },
  { value: "bo", label: "Tibetan" },
  { value: "ug", label: "Uyghur" },
  { value: "ky", label: "Kyrgyz" },
  { value: "tg", label: "Tajik" },
  { value: "tk", label: "Turkmen" },
  { value: "aa", label: "Afar" },
  { value: "ti", label: "Tigrinya" },
  { value: "so", label: "Somali" },
  { value: "om", label: "Oromo" },
];

export const CURRENCIES: LabelValueItem[] = [
  { value: "USD", label: "USD", descriptor: "US Dollar" },
  { value: "EUR", label: "EUR", descriptor: "Euro" },
  { value: "MUR", label: "MUR", descriptor: "Mauritian Rupee" },
  { value: "KES", label: "KES", descriptor: "Kenyan Shilling" },
  { value: "GBP", label: "GBP", descriptor: "British Pound" },
  { value: "JPY", label: "JPY", descriptor: "Japanese Yen" },
  { value: "CAD", label: "CAD", descriptor: "Canadian Dollar" },
  { value: "AUD", label: "AUD", descriptor: "Australian Dollar" },
  { value: "CHF", label: "CHF", descriptor: "Swiss Franc" },
  { value: "CNY", label: "CNY", descriptor: "Chinese Yuan" },
  { value: "SEK", label: "SEK", descriptor: "Swedish Krona" },
  { value: "NZD", label: "NZD", descriptor: "New Zealand Dollar" },
  { value: "NOK", label: "NOK", descriptor: "Norwegian Krone" },
  { value: "MXN", label: "MXN", descriptor: "Mexican Peso" },
  { value: "SGD", label: "SGD", descriptor: "Singapore Dollar" },
  { value: "HKD", label: "HKD", descriptor: "Hong Kong Dollar" },
  { value: "KRW", label: "KRW", descriptor: "South Korean Won" },
  { value: "TRY", label: "TRY", descriptor: "Turkish Lira" },
  { value: "RUB", label: "RUB", descriptor: "Russian Ruble" },
  { value: "INR", label: "INR", descriptor: "Indian Rupee" },
  { value: "BRL", label: "BRL", descriptor: "Brazilian Real" },
  { value: "ZAR", label: "ZAR", descriptor: "South African Rand" },
  { value: "AED", label: "AED", descriptor: "UAE Dirham" },
  { value: "SAR", label: "SAR", descriptor: "Saudi Riyal" },
  { value: "QAR", label: "QAR", descriptor: "Qatari Riyal" },
  { value: "KWD", label: "KWD", descriptor: "Kuwaiti Dinar" },
  { value: "BHD", label: "BHD", descriptor: "Bahraini Dinar" },
  { value: "OMR", label: "OMR", descriptor: "Omani Rial" },
  { value: "ILS", label: "ILS", descriptor: "Israeli Shekel" },
  { value: "PLN", label: "PLN", descriptor: "Polish Zloty" },
  { value: "CZK", label: "CZK", descriptor: "Czech Koruna" },
  { value: "HUF", label: "HUF", descriptor: "Hungarian Forint" },
  { value: "RON", label: "RON", descriptor: "Romanian Leu" },
  { value: "BGN", label: "BGN", descriptor: "Bulgarian Lev" },
  { value: "HRK", label: "HRK", descriptor: "Croatian Kuna" },
  { value: "DKK", label: "DKK", descriptor: "Danish Krone" },
  { value: "ISK", label: "ISK", descriptor: "Icelandic Króna" },
  { value: "CLP", label: "CLP", descriptor: "Chilean Peso" },
  { value: "COP", label: "COP", descriptor: "Colombian Peso" },
  { value: "PEN", label: "PEN", descriptor: "Peruvian Sol" },
  { value: "ARS", label: "ARS", descriptor: "Argentine Peso" },
  { value: "UYU", label: "UYU", descriptor: "Uruguayan Peso" },
  { value: "PYG", label: "PYG", descriptor: "Paraguayan Guarani" },
  { value: "BOB", label: "BOB", descriptor: "Bolivian Boliviano" },
  { value: "VEF", label: "VEF", descriptor: "Venezuelan Bolívar" },
  { value: "CRC", label: "CRC", descriptor: "Costa Rican Colón" },
  { value: "PAB", label: "PAB", descriptor: "Panamanian Balboa" },
  { value: "GTQ", label: "GTQ", descriptor: "Guatemalan Quetzal" },
  { value: "HNL", label: "HNL", descriptor: "Honduran Lempira" },
  { value: "NIO", label: "NIO", descriptor: "Nicaraguan Córdoba" },
  { value: "SVC", label: "SVC", descriptor: "Salvadoran Colón" },
  { value: "DOP", label: "DOP", descriptor: "Dominican Peso" },
];
