export const JWT_REFRESH_TOKEN_VALIDITY_DAYS: number = 7;
export const JWT_ACCESS_TOKEN_VALIDITY_MINUTES: number = 60;

export const RAW_RESPONSE_REFLECTOR_KEY = 'RAW_RESPONSE';
export const RESPONSE_SUMMARY_REFLECTOR_KEY = 'WRAPPED_RESPONSE';
