export const SSE_EVENT_VARIANT = {
	CONNECTED: 'CONNECTED',
	BILL_CREATED: 'BILL_CREATED',
	BILL_DUE_SOON: 'BILL_DUE_SOON',
	WALLET_CREATED: 'WALLET_CREATED',
	WALLET_UPDATED: 'WALLET_UPDATED',
	WALLET_DELETED: 'WALLET_DELETED',
	NEGATIVE_BALANCE: 'NEGATIVE_BALANCE',
	NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
	NOTIFICATION_UPDATED: 'NOTIFICATION_UPDATED',
	NOTIFICATION_DELETED: 'NOTIFICATION_DELETED',
	NOTIFICATIONS_REFRESHED: 'NOTIFICATIONS_REFRESHED'
} as const;

export type SSE_EVENT_VARIANT = (typeof SSE_EVENT_VARIANT)[keyof typeof SSE_EVENT_VARIANT];

export const SSE_EVENT_NAME = {
	[SSE_EVENT_VARIANT.CONNECTED]: 'connected',
	[SSE_EVENT_VARIANT.BILL_CREATED]: 'bill.created',
	[SSE_EVENT_VARIANT.BILL_DUE_SOON]: 'bill.due-soon',
	[SSE_EVENT_VARIANT.WALLET_CREATED]: 'wallet.created',
	[SSE_EVENT_VARIANT.WALLET_UPDATED]: 'wallet.updated',
	[SSE_EVENT_VARIANT.WALLET_DELETED]: 'wallet.deleted',
	[SSE_EVENT_VARIANT.NEGATIVE_BALANCE]: 'negative-balance',
	[SSE_EVENT_VARIANT.NOTIFICATION_CREATED]: 'notification.created',
	[SSE_EVENT_VARIANT.NOTIFICATION_UPDATED]: 'notification.updated',
	[SSE_EVENT_VARIANT.NOTIFICATION_DELETED]: 'notification.deleted',
	[SSE_EVENT_VARIANT.NOTIFICATIONS_REFRESHED]: 'notifications.refreshed'
} as const satisfies Record<SSE_EVENT_VARIANT, string>;

export type SSE_EVENT_NAME = (typeof SSE_EVENT_NAME)[keyof typeof SSE_EVENT_NAME];
