export const DEFAULT_INCOME_CATEGORIES = [
    'salary',
    'freelance',
    'business',
    'investments',
    'rental_income',
    'refunds',
    'bonuses',
    'gifts',
];
export const DEFAULT_EXPENSE_CATEGORIES = [
    'housing',
    'utilities',
    'groceries',
    'transportation',
    'health',
    'insurance',
    'debt_payments',
    'subscriptions',
    'entertainment',
    'dining',
    'shopping',
    'education',
    'personal_care',
    'travel',
    'gifts_donations',
    'miscellaneous',
];
